### ISSUE TITLE
AtCoderTags_Helper が ac-perdictor と干渉する

### ISSUE THREAD

**Issue by kmyk** [null-null-programming/AtCoderTags#1]
@key-moon さんの [ac-predictor](https://greasyfork.org/en/scripts/369954-ac-predictor) が導入されていると [AtCoderTags_Helper](https://greasyfork.org/ja/scripts/393121-atcodertags-helper) が動きません。ac-perdictor は動きます。どちらが問題なのかは分かりませんが、 ac-predictor を入れている人は多そう (少なくともユーザ層はかなり被りそう) なので対策した方がいいと思います。
[ac-predictor-minimal](https://greasyfork.org/en/scripts/386999-ac-predictor-minimal) の方となら干渉はしません。

**Comment by null-null-programming** [comment]
ありがとうございます。
早急に対処したいと思います。

**Comment by key-moon** [comment]
コードを見た感じpredictorのsidemenuのdivを直接コピーしてきている感じがしていて、idが干渉してるように見えます 多分idを変えると解決するはずです
predictorのようにsidemenuに載せたいのであれば、以下のライブラリを公開しているので使うと良いと思います
https://greasyfork.org/ja/scripts/386715-atcoder-sidemenu

**Comment by null-null-programming** [comment]
すみません・・・idは別のものに変えるべきでした。
idを変更したのでおそらく干渉しなくなったと思われます。

ライブラリありがとうございます。
使ってみます。
