### ISSUE TITLE
herokuサービス稼働状況と投票DBの状態について

### ISSUE THREAD

**Issue by mo124121** [null-null-programming/AtCoderTags#13]
@null-null-programming 

いつもAtCoderTagsを便利に使わせていただいております。
ありがとうございます。

ただ、今朝アクセスしようとしたところ、下記の状態でした。
![image](https://github.com/null-null-programming/AtCoderTags/assets/101929016/d83fa6b6-e8b3-45cb-9232-6e12a7a3537e)

お忙しいところ大変申し訳ないのですが、
現状のherokuの状態はどのような状態か確認頂けないでしょうか？
特に、投票データを保持しているDBは生存していますでしょうか？

大前提として、
有志で開発・提供いただいているものである以上、
こういう事態になっていることを何ら責めたいわけでは全く、
どういう結末になるにせよ感謝しかございません。

ただ、投票という形でいろんな人のコントリビューションを経て出来上がった情報が、
このまま失われるのは非常にもったいないと感じてまして、
そのあたり何かできることはないかと思い、ご連絡させて頂いている次第です。

**Comment by null-null-programming** [comment]
ご連絡ありがとうございます。
すみません、こちらの手違いで４月分の支払いが落とされておらず停止した模様です。
再稼働させましたので、また使っていただければと思います。

**Comment by mo124121** [comment]
ご対応頂きありがとうございます。
データ飛んでないかとかあれこれ考えてしまったのですが、杞憂でよかったです。
