### ISSUE TITLE
もっと細かいタグが付いてほしい

### ISSUE THREAD

**Issue by kmyk** [null-null-programming/AtCoderTags#2]
たとえば「どんなデータ構造でもいいからなにかデータ構造に関連した問題を解きたい」と思うことは少ないはずです。タグとして望まれているのは「セグメント木の問題を解きたい」「union-find 木の問題を解きたい」といったときに使えるものだと思います。
このため「セグメント木」「union-find 木」とか「遅延伝播セグメント木」「O(N + Q log N)」のようなより細かいタグが付くようになるとうれしいです。

**Comment by null-null-programming** [comment]
ありがとうございます！
タグのより細かな分類分けは現在計画中で、設計を考えているところです。
すぐには出来ないと思いますが、頑張りたいと思います。

**Comment by null-null-programming** [comment]
より細かいタグを付けました。
